name: Docker Image CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
# ===============================================================
#   Building Dev Image
# ===============================================================
  build_dev:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        # I use GHCR_TOKEN instead of GITHUB_TOKEN because otherwise build-push-action 
        # fails to push new image.
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build ubuntu-dev
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ghcr.io/${{ github.actor }}/ubuntu-dev:latest
        file: u20.04-dev.Dockerfile

    - name: Build alpine-dev
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ghcr.io/${{ github.actor }}/alpine-dev:latest
        file: alpine-dev.Dockerfile
