name: Docker Image CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions: 
  packages: write

jobs:
# ===============================================================
#   Building Dev Image
# ===============================================================
  build_dev:

    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    # https://github.com/docker/setup-qemu-action
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:          
          platforms: arm64,amd64
    -
      name: Available platforms
      run: echo ${{ steps.qemu.outputs.platforms }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build ubuntu-dev
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ghcr.io/${{ github.actor }}/ubuntu-dev:20
        file: u20.04-dev.Dockerfile

    - name: Build alpine-dev
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ghcr.io/${{ github.actor }}/alpine-dev:latest
        file: alpine-dev.Dockerfile
